CODEGEN_ENV = $(shell /bin/bash detect-codegen-env.sh)

build:
	npm run build:$(CODEGEN_ENV)

external:
	npm run build:external

internal:
	npm run build:internal

start:
	npm run start

clean:
	npm run clean
